### ISSUE TITLE
init/3 undefined

### ISSUE THREAD

**Issue by stuart-thackray** [freecnpro/ObserverWeb#2]
Hi,

I am getting observerweb_handler,init,3 undefined, I see you are pulling specific tags of cowboy, so can't figure out why I am not getting it to work.

I am running R18; on linux.

=ERROR REPORT==== 2-Feb-2016::16:03:07 ===
Ranch listener http had connection process started with cowboy_protocol:start_link/4 at <0.1175.0> exit with reason: {[{reason,undef},{mfa,{observerweb_handler,init,3}},{stacktrace,[{observerweb_handler,init,[{tcp,http},{http_req,#Port<0.3104>,ranch_tcp,keepalive,<0.1175.0>,<<"POST">>,'HTTP/1.1',{{127,0,0,1},44282},<<"127.0.0.1">>,undefined,8080,<<"/info">>,undefined,<<>>,undefined,[],[{<<"host">>,<<"127.0.0.1:8080">>},{<<"connection">>,<<"keep-alive">>},{<<"content-length">>,<<"17">>},{<<"origin">>,<<"http://127.0.0.1:8080">>},{<<"user-agent">>,<<"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36">>},{<<"content-type">>,<<"text/plain;charset=UTF-8">>},{<<"accept">>,<<"_/_">>},{<<"referer">>,<<"http://127.0.0.1:8080/">>},{<<"accept-encoding">>,<<"gzip, deflate">>},{<<"accept-language">>,<<"en-US,en;q=0.8">>}],[{<<"connection">>,[<<"keep-alive">>]}],undefined,[],waiting,<<"action=get_malloc">>,undefined,false,waiting,[],<<>>,undefined},[]],[]},{cowboy_handler,handler_init,4,[{file,"src/cowboy_handler.erl"},{line,64}]},{cowboy_protocol,execute,4,[{file,"src/cowboy_protocol.erl"},{line,442}]}]},{req,[{socket,#Port<0.3104>},{transport,ranch_tcp},{connection,keepalive},{pid,<0.1175.0>},{method,<<"POST">>},{version,'HTTP/1.1'},{peer,{{127,0,0,1},44282}},{host,<<"127.0.0.1">>},{host_info,undefined},{port,8080},{path,<<"/info">>},{path_info,undefined},{qs,<<>>},{qs_vals,undefined},{bindings,[]},{headers,[{<<"host">>,<<"127.0.0.1:8080">>},{<<"connection">>,<<"keep-alive">>},{<<"content-length">>,<<"17">>},{<<"origin">>,<<"http://127.0.0.1:8080">>},{<<"user-agent">>,<<"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36">>},{<<"content-type">>,<<"text/plain;charset=UTF-8">>},{<<"accept">>,<<"_/_">>},{<<"referer">>,<<"http://127.0.0.1:8080/">>},{<<"accept-encoding">>,<<"gzip, deflate">>},{<<"accept-language">>,<<"en-US,en;q=0.8">>}]},{p_headers,[{<<"connection">>,[<<"keep-alive">>]}]},{cookies,undefined},{meta,[]},{body_state,waiting},{buffer,<<"action=get_malloc">>},{multipart,undefined},{resp_compress,false},{resp_state,waiting},{resp_headers,[]},{resp_body,<<>>},{onresponse,undefined}]},{opts,[]}],[{cowboy_protocol,execute,4,[{file,"src/cowboy_protocol.erl"},{line,442}]}]}

**Comment by w1o7l5** [comment]
@stuart-thackray Please use cowboy brach **master**, no 1.0.4.  It's my commit error :(
